/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.11 */
package parser;

public interface ParserTreeConstants
{
  public int JJTFILE = 0;
  public int JJTARRAYLITERAL = 1;
  public int JJTASSOCIATIVEEXPR = 2;
  public int JJTRANGELITERAL = 3;
  public int JJTVOID = 4;
  public int JJTEXPRESSIONSTATEMENT = 5;
  public int JJTSTATEMENT = 6;
  public int JJTERROR_SKIPTO = 7;
  public int JJTSELECTSTATEMENT = 8;
  public int JJTCTRLDECL = 9;
  public int JJTWHILEDOSTATEMENT = 10;
  public int JJTDOWHILESTATEMENT = 11;
  public int JJTFORSTATEMENT = 12;
  public int JJTITERABLEEXPR = 13;
  public int JJTLABELSTATEMENT = 14;
  public int JJTBREAKSTATEMENT = 15;
  public int JJTCONTINUESTATEMENT = 16;
  public int JJTPARAMFORSTATEMENT = 17;
  public int JJTUSESTATEMENT = 18;
  public int JJTLIMITATIONCLAUSE = 19;
  public int JJTEXCLUDE = 20;
  public int JJTMODULEORENUMNAME = 21;
  public int JJTRENAMEBASE = 22;
  public int JJTIMPORTSTATEMENT = 23;
  public int JJTIMPORTEXPR = 24;
  public int JJTMODULEORSYMBOLBASE = 25;
  public int JJTMODULEORSYMBOLRENAME = 26;
  public int JJTUNQUALIFIEDLIST = 27;
  public int JJTDEFERSTATEMENT = 28;
  public int JJTEMPTYSTATEMENT = 29;
  public int JJTRETURNSTATEMENT = 30;
  public int JJTYIELDSTATEMENT = 31;
  public int JJTMODULEDECLARATIONSTATEMENT = 32;
  public int JJTPROCEDUREDECLARATIONSTATEMENT = 33;
  public int JJTWHERECLAUSE = 34;
  public int JJTRETURNTYPE = 35;
  public int JJTEXTERNALPROCEDUREDECLARATIONSTATEMENT = 36;
  public int JJTEXPORTEDPROCEDUREDECLARATIONSTATEMENT = 37;
  public int JJTITERATORDECLARATIONSTATEMENT = 38;
  public int JJTYIELDTYPE = 39;
  public int JJTYIELDINTENT = 40;
  public int JJTMETHODDECLARATIONSTATEMENT = 41;
  public int JJTTYPEBINDING = 42;
  public int JJTTHISINTENT = 43;
  public int JJTTYPEDECLARATIONSTATEMENT = 44;
  public int JJTENUMDECLARATIONSTATEMENT = 45;
  public int JJTENUMBODY = 46;
  public int JJTENUMCONSTANT = 47;
  public int JJTINITPART = 48;
  public int JJTCLASSDECLARATIONSTATEMENT = 49;
  public int JJTCLASSINHERIT = 50;
  public int JJTBASICCLASSTYPE = 51;
  public int JJTNAMEDEXPRESSION = 52;
  public int JJTRECORDDECLARATIONSTATEMENT = 53;
  public int JJTEXTERNALRECORDDECLARATIONSTATEMENT = 54;
  public int JJTIDENTIFIER = 55;
  public int JJTSIMPLERECORDDECLARATIONSTATEMENT = 56;
  public int JJTUNIONDECLARATIONSTATEMENT = 57;
  public int JJTTYPEALIASDECLARATIONSTATEMENT = 58;
  public int JJTEXTERNALTYPEALIASDECLARATIONSTATEMENT = 59;
  public int JJTTYPEALIASDECLARATION = 60;
  public int JJTVARIABLEDECLARATIONSTATEMENT = 61;
  public int JJTCONFIGEXTERNOREXPORT = 62;
  public int JJTVARIABLEKIND = 63;
  public int JJTVARIABLEDECLARATIONLIST = 64;
  public int JJTVARIABLEDECLARATION = 65;
  public int JJTTYPEPART = 66;
  public int JJTINITIALIZATIONPART = 67;
  public int JJTIDENTIFIERLIST = 68;
  public int JJTTUPLEGROUPEDIDENTIFIERLIST = 69;
  public int JJTREMOTEVARIABLEDECLARATIONSTATEMENT = 70;
  public int JJTONSTATEMENT = 71;
  public int JJTCOBEGINSTATEMENT = 72;
  public int JJTTASKINTENTCLAUSE = 73;
  public int JJTTASKINTENTITEM = 74;
  public int JJTCLASSTYPE = 75;
  public int JJTREDUCESCANOPERATOR = 76;
  public int JJTTASKINTENTLIST = 77;
  public int JJTTASKPRIVATEVARDECL = 78;
  public int JJTTASKPRIVATEVARKIND = 79;
  public int JJTCOFORALLSTATEMENT = 80;
  public int JJTITERATABLEEXPRESSION = 81;
  public int JJTINDEXVARDECLARATION = 82;
  public int JJTBEGINSTATEMENT = 83;
  public int JJTSYNCSTATEMENT = 84;
  public int JJTSYNCTYPE = 85;
  public int JJTSERIALSTATEMENT = 86;
  public int JJTATOMICTYPE = 87;
  public int JJTSINGLETYPE = 88;
  public int JJTFORALLSTATEMENT = 89;
  public int JJTDELETESTATEMENT = 90;
  public int JJTMANAGESTATEMENT = 91;
  public int JJTMANAGEREXPRESSION = 92;
  public int JJTPARENTHESIZEDEXPRESSION = 93;
  public int JJTASSIGNOPERATORS = 94;
  public int JJTBLOCKSTATEMENT = 95;
  public int JJTIFSTATEMENT = 96;
  public int JJTPRIVACYSPECIFIER = 97;
  public int JJTRETURNINTENT = 98;
  public int JJTSYNCHRONIZATIONTYPE = 99;
  public int JJTDATAPARALLELTYPE = 100;
  public int JJTMAPPEDDOMAINTYPE = 101;
  public int JJTINDEXTYPE = 102;
  public int JJTRANGETYPE = 103;
  public int JJTTUPLETYPE = 104;
  public int JJTPRIMITIVETYPEPARAMETERPART = 105;
  public int JJTINTEGERPARAMETEREXPRESSION = 106;
  public int JJTPRIMITIVETYPE = 107;
  public int JJTOPERATOR = 108;
  public int JJTARGUMENTLIST = 109;
  public int JJTFORMALTYPE = 110;
  public int JJTVARIABLEARGUMENTEXPR = 111;
  public int JJTFORMAL = 112;
  public int JJTFORMALINTENT = 113;
  public int JJTPROCKIND = 114;
  public int JJTEXPRESSION = 115;
  public int JJTMAPPEDDOMAINEXPRESSION = 116;
  public int JJTDMAPVALUE = 117;
  public int JJTDOMAINEXPRESSION = 118;
  public int JJTDOMAINALIGNMENTEXPRESSION = 119;
  public int JJTDOMAINASSIGNMENTEXPRESSION = 120;
  public int JJTDOMAINSLICEEXPRESSION = 121;
  public int JJTSLICINGINDEXSET = 122;
  public int JJTDOMAINSTRIDINGEXPRESSION = 123;
  public int JJTDOMAINTYPE = 124;
  public int JJTSIMPLESUBDOMAINTYPE = 125;
  public int JJTSPARSESUBDOMAINTYPE = 126;
  public int JJTBASEDOMAINTYPE = 127;
  public int JJTRECTANGULARDOMAINTYPE = 128;
  public int JJTASSOCIATIVEDOMAINTYPE = 129;
  public int JJTASSOCIATIVEINDEXTYPE = 130;
  public int JJTLOCALEQUERYEXPRESSION = 131;
  public int JJTTUPLEEXPANDEXPRESSION = 132;
  public int JJTTUPLEEXPRESSION = 133;
  public int JJTTUPLECOMPONENTLIST = 134;
  public int JJTTUPLECOMPONENT = 135;
  public int JJTMODULEACCESSEXPRESSION = 136;
  public int JJTMODULEIDENTIFIERLIST = 137;
  public int JJTREDUCEEXPRESSION = 138;
  public int JJTSCANEXPRESSION = 139;
  public int JJTIFEXPRESSION = 140;
  public int JJTFOREXPRESSION = 141;
  public int JJTFORALLEXPRESSION = 142;
  public int JJTLETEXPRESSION = 143;
  public int JJTBINARYEXPRESSION = 144;
  public int JJTBINARYOPERATOR = 145;
  public int JJTUNARYEXPRESSION = 146;
  public int JJTUNARYOPERATOR = 147;
  public int JJTCASTEXPRESSION = 148;
  public int JJTQUERYEXPRESSION = 149;
  public int JJTNEWEXPRESSION = 150;
  public int JJTENUMCONSTANTEXPRESSION = 151;
  public int JJTLITERALEXPRESSION = 152;
  public int JJTREALLITERAL = 153;
  public int JJTIMAGINARYLITERAL = 154;
  public int JJTSTRINGLITERAL = 155;
  public int JJTBOOLLITERAL = 156;
  public int JJTINTEGERLITERAL = 157;
  public int JJTRECTANGULARDOMAINLITERAL = 158;
  public int JJTRANGEEXPRESSIONLIST = 159;
  public int JJTRANGEEXPRESSION = 160;
  public int JJTCOUNTEDRANGEEXPRESSION = 161;
  public int JJTSTRIDEDRANGEEXPRESSION = 162;
  public int JJTSLICEDRANGEEXPRESSION = 163;
  public int JJTALIGNEDRANGEEXPRESSION = 164;
  public int JJTSTEPEXPRESSION = 165;
  public int JJTDOMAINLITERAL = 166;
  public int JJTASSOCIATIVEDOMAINLITERAL = 167;
  public int JJTASSOCIATIVEEXPRESSIONLIST = 168;
  public int JJTNONRANGEEXPRESSION = 169;
  public int JJTBYTESLITERAL = 170;


  public String[] jjtNodeName = {
    "File",
    "ArrayLiteral",
    "AssociativeExpr",
    "RangeLiteral",
    "void",
    "ExpressionStatement",
    "Statement",
    "error_skipto",
    "SelectStatement",
    "CTRLDecl",
    "WhileDoStatement",
    "DoWhileStatement",
    "ForStatement",
    "IterableExpr",
    "LabelStatement",
    "BreakStatement",
    "ContinueStatement",
    "ParamForStatement",
    "UseStatement",
    "LimitationClause",
    "Exclude",
    "ModuleOrEnumName",
    "RenameBase",
    "ImportStatement",
    "ImportExpr",
    "ModuleOrSymbolBase",
    "ModuleOrSymbolRename",
    "UnqualifiedList",
    "DeferStatement",
    "EmptyStatement",
    "ReturnStatement",
    "YieldStatement",
    "ModuleDeclarationStatement",
    "ProcedureDeclarationStatement",
    "WhereClause",
    "ReturnType",
    "ExternalProcedureDeclarationStatement",
    "ExportedProcedureDeclarationStatement",
    "IteratorDeclarationStatement",
    "YieldType",
    "YieldIntent",
    "MethodDeclarationStatement",
    "TypeBinding",
    "ThisIntent",
    "TypeDeclarationStatement",
    "EnumDeclarationStatement",
    "EnumBody",
    "EnumConstant",
    "InitPart",
    "ClassDeclarationStatement",
    "ClassInherit",
    "BasicClassType",
    "NamedExpression",
    "RecordDeclarationStatement",
    "ExternalRecordDeclarationStatement",
    "Identifier",
    "SimpleRecordDeclarationStatement",
    "UnionDeclarationStatement",
    "TypeAliasDeclarationStatement",
    "ExternalTypeAliasDeclarationStatement",
    "TypeAliasDeclaration",
    "VariableDeclarationStatement",
    "ConfigExternOrExport",
    "VariableKind",
    "VariableDeclarationList",
    "VariableDeclaration",
    "TypePart",
    "InitializationPart",
    "IdentifierList",
    "TupleGroupedIdentifierList",
    "RemoteVariableDeclarationStatement",
    "OnStatement",
    "CobeginStatement",
    "TaskIntentClause",
    "TaskIntentItem",
    "ClassType",
    "ReduceScanOperator",
    "TaskIntentList",
    "TaskPrivateVarDecl",
    "TaskPrivateVarKind",
    "CoforallStatement",
    "IteratableExpression",
    "IndexVarDeclaration",
    "BeginStatement",
    "SyncStatement",
    "SyncType",
    "SerialStatement",
    "AtomicType",
    "SingleType",
    "ForallStatement",
    "DeleteStatement",
    "ManageStatement",
    "ManagerExpression",
    "ParenthesizedExpression",
    "AssignOperators",
    "BlockStatement",
    "IfStatement",
    "PrivacySpecifier",
    "ReturnIntent",
    "SynchronizationType",
    "DataparallelType",
    "MappedDomainType",
    "IndexType",
    "RangeType",
    "TupleType",
    "PrimitiveTypeParameterPart",
    "IntegerParameterExpression",
    "PrimitiveType",
    "Operator",
    "ArgumentList",
    "FormalType",
    "VariableArgumentExpr",
    "Formal",
    "FormalIntent",
    "ProcKind",
    "Expression",
    "MappedDomainExpression",
    "DmapValue",
    "DomainExpression",
    "DomainAlignmentExpression",
    "DomainAssignmentExpression",
    "DomainSliceExpression",
    "SlicingIndexSet",
    "DomainStridingExpression",
    "DomainType",
    "SimpleSubdomainType",
    "SparseSubdomainType",
    "BaseDomainType",
    "RectangularDomainType",
    "AssociativeDomainType",
    "AssociativeIndexType",
    "LocaleQueryExpression",
    "TupleExpandExpression",
    "TupleExpression",
    "TupleComponentList",
    "TupleComponent",
    "ModuleAccessExpression",
    "ModuleIdentifierList",
    "ReduceExpression",
    "ScanExpression",
    "IfExpression",
    "ForExpression",
    "ForallExpression",
    "LetExpression",
    "BinaryExpression",
    "BinaryOperator",
    "UnaryExpression",
    "UnaryOperator",
    "CastExpression",
    "QueryExpression",
    "NewExpression",
    "EnumConstantExpression",
    "LiteralExpression",
    "RealLiteral",
    "ImaginaryLiteral",
    "StringLiteral",
    "BoolLiteral",
    "IntegerLiteral",
    "RectangularDomainLiteral",
    "RangeExpressionList",
    "RangeExpression",
    "CountedRangeExpression",
    "StridedRangeExpression",
    "SlicedRangeExpression",
    "AlignedRangeExpression",
    "StepExpression",
    "DomainLiteral",
    "AssociativeDomainLiteral",
    "AssociativeExpressionList",
    "NonRangeExpression",
    "BytesLiteral",
  };
}
/* JavaCC - OriginalChecksum=11929c4404934a3f8ff79d0407fc5698 (do not edit this line) */
